### PR TITLE
Updated checksums

### PR DESCRIPTION
**Pull request by ovk6**
Updated versions.yaml because checksums for source tarballs downloaded from github.com/.../.../archive can change over time.

### CODE REVIEW

**Comment by wgrzelak** [comment]
@jprzychodzen do you have more context on this, right?

**Comment by jprzychodzen** [comment]
@wgrzelak No I do not. There was an issue with changing checksum, but it was an empty file.

@ovk6 What is the reason for this checksum to change? Changing checksum means that file has changed.

**Comment by ovk6** [comment]
@jprzychodzen 
Nope, it was not about empty files. What you showed me locally had nothing to do with tests run for container and didn't occur during tests.

Anyway it looks like we have issue similar to https://github.com/easybuilders/easybuild-easyconfigs/issues/5151 or https://github.com/spack/spack/issues/5411, that also hit several other projects.
Shortly we cannot rely on checksums for files downloaded from github.com/.../.../archive, because they are generated dynamically and can change over time.

**Review by wgrzelak — CHANGES_REQUESTED** [review]
Needed to be clarify.

**Comment by ovk6** [comment]
Outdated

**Pull request closed without merging**
